### PR TITLE
Pending

### LINKED ISSUE #589: bad tx returns non-error
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]
branch: `development`

__Steps to reproduce:__

1. start the network with `./init.sh`
2. send multiple transactions with the same nonce

__Expected behavior:__ [What you expected to happen]

should give an error (with possible err msg). this error message should give:
`invalid nonce; got 1, expected 2`

__Actual behavior:__ [What actually happened]

returns a tx hash:
`{"jsonrpc":"2.0","id":1,"result":"0xeea0292cffd6a3724cb9e6678127a30baaa17430b59e23742079448d22dba8cf"}`

__Additional info:__ [Include gist of relevant config, logs, etc.]

### PR DESCRIPTION
**Pull request by araskachoi**
Closes: #XXX

## Description

[x]eth_getBalance
[x]eth_getTransactionCount
[x]eth_getBlockTransactionCountByNumber
[]eth_call
[]eth_estimateGas
[x]eth_getBlockByNumber
- if querying "pending", returns information about the next pending block 
- timestamp will be set to: `0001-01-01 00:00:00 +0000 UTC`
- size will be set to: `0x`

[x]eth_getTransactionByHash
- querying a pending transaction hash will give `blockNumber = nil`

[x]eth_getTransactionByBlockNumberAndIndex
- pending query will return `blockhash = nil` and  `blocknumber = nil`

[x]eth_sendTransaction
- will set pending nonce when none is provided
- errors out when an incorrect nonce is given (fixes https://github.com/cosmos/ethermint/issues/589)

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

File: rpc/namespaces/eth/api.go [hunk 1]
```diff
@@ -888,3 +1172,38 @@ func (api *PublicEthereumAPI) generateFromArgs(args rpctypes.SendTxArgs) (*evmty
 
 	return &msg, nil
 }
+
+// getPendingBlock returns the blocknumber and pending
+// if -1, returns latest blocknumber and pending is set to true
+// if 0, returns latest blocknumber and pending is set to false
+// if not 0 or -1, returns blocknumber and pendisng is set to false
+func (api *PublicEthereumAPI) getPendingBlock(blockNum rpctypes.BlockNumber) (*int64, bool, error) {
```
Comment (fedekunze) [inline rpc/namespaces/eth/api.go]: I think this should live in `backend.go`

File: rpc/namespaces/eth/api.go [hunk 2]
```diff
@@ -300,17 +326,38 @@ func (api *PublicEthereumAPI) GetBlockTransactionCountByHash(hash common.Hash) *
...
+
+	// get the pending transaction count
+	pendingTxs, err := api.backend.PendingTransactions()
 	if err != nil {
 		return nil
 	}
 
-	n := hexutil.Uint(len(resBlock.Block.Txs))
-	return &n
+	txCount := hexutil.Uint(len(pendingTxs) / 2)
```
Comment (fedekunze) [inline rpc/namespaces/eth/api.go]: why is this?

File: rpc/namespaces/eth/api.go [hunk 3]
```diff
@@ -300,17 +326,38 @@ func (api *PublicEthereumAPI) GetBlockTransactionCountByHash(hash common.Hash) *
...
+
+	var height int64
+	if blockNum != rpctypes.PendingBlockNumber {
+		if blockNum == rpctypes.LatestBlockNumber {
+			bn, err := api.backend.BlockNumber()
+			if err != nil {
+				return nil
+			}
+			bnCleaned := strings.Replace(bn.String(), "0x", "", -1)
+			height, err = strconv.ParseInt(bnCleaned, 16, 64)
```
Comment (fedekunze) [inline rpc/namespaces/eth/api.go]: you can use the util function `api.backend.LatestBlockNumber()`

Comment (araskachoi) [reply rpc/namespaces/eth/api.go]: you are 100% right, forgot you move that to backend!

File: rpc/namespaces/eth/api.go (hunk 2 above)
Comment (araskachoi) [reply rpc/namespaces/eth/api.go]: strange behavior that i mentioned a month or 2 back but the pending queue is filled with `<nil>` for as many transactions are in the queue. So for example, if you send 2 transactions, the output of the pendingQueue will be `[<nil>, <nil>, &<0x123> $<0x456>]`
so the division is just a way to disregard the `nil`'s

Comment (fedekunze) [reply rpc/namespaces/eth/api.go]: uh that's odd? we should fix the underlying issue then

File: rpc/backend/backend.go [hunk 4]
```diff
@@ -196,7 +196,7 @@ func (b *EthermintBackend) PendingTransactions() ([]*rpctypes.Transaction, error
 		return nil, err
 	}
 
-	transactions := make([]*rpctypes.Transaction, pendingTxs.Count)
+	transactions := make([]*rpctypes.Transaction, 0)
 	for _, tx := range pendingTxs.Txs {
```
Comment (noot) [inline rpc/backend/backend.go:200]: you could leave the `transactions := ...` line the same as before, then change the `for` to be `for i, tx := ...` and assign to `transactions[i]` instead of appending

File: rpc/backend/backend.go [hunk 5]
```diff
@@ -196,8 +196,8 @@ func (b *EthermintBackend) PendingTransactions() ([]*rpctypes.Transaction, error
 		return nil, err
 	}
 
-	transactions := make([]*rpctypes.Transaction, pendingTxs.Count)
-	for _, tx := range pendingTxs.Txs {
+	transactions := make([]*rpctypes.Transaction, 0)
```
Comment (noot) [inline rpc/backend/backend.go:199]: update length to `pendingTxs.Count`?

File: rpc/namespaces/eth/api.go [hunk 6]
```diff
@@ -234,6 +240,28 @@ func (api *PublicEthereumAPI) GetBalance(address common.Address, blockNum rpctyp
...
+	for _, tx := range pendingTxs {
+		if tx == nil {
+			continue
+		}
+
+		if tx.From == address {
+			val = new(big.Int).Sub(val, tx.Value.ToInt())
+		} else if *tx.To == address {
+			val = new(big.Int).Add(val, tx.Value.ToInt())
+		}
```
Comment (noot) [inline rpc/namespaces/eth/api.go]: there might be an edge case here where the to and the from are the same, so change this to two `if`s instead of an `if.. else if`

File: rpc/namespaces/eth/api.go [hunk 7]
```diff
@@ -571,14 +634,70 @@ func (api *PublicEthereumAPI) GetBlockByHash(hash common.Hash, fullTx bool) (map
...
+		return nil, err
+	}
+
+	// latest block info
+	latestBlock, err := api.clientCtx.Client.Block(&height)
+	if err != nil {
+		return nil, err
+	}
+
+	unconfirmedTxs, err := api.clientCtx.Client.UnconfirmedTxs(100)
```
Comment (noot) [inline rpc/namespaces/eth/api.go]: what is the 100?

File: rpc/namespaces/eth/api.go [hunk 8]
```diff
@@ -886,3 +1026,92 @@ func (api *PublicEthereumAPI) generateFromArgs(args rpctypes.SendTxArgs) (*evmty
 
 	return &msg, nil
 }
+
+// pendingMsgs constructs
```
Comment (noot) [inline rpc/namespaces/eth/api.go]: ?

File: rpc/types/block.go [hunk 9]
```diff
@@ -18,6 +18,9 @@ const (
 
 	// EarliestBlockNumber mapping from "earliest" to 1 for tm query (earliest query not supported)
 	EarliestBlockNumber = BlockNumber(1)
+
+	// PendingBlockNumber mapping from "pending" to 1 for tm query -- repeating 1 for now, TDB
```
Comment (noot) [inline rpc/types/block.go]: update comment

File: rpc/backend/backend.go [hunk 10]
```diff
@@ -197,7 +197,7 @@ func (b *EthermintBackend) PendingTransactions() ([]*rpctypes.Transaction, error
 	}
 
 	transactions := make([]*rpctypes.Transaction, pendingTxs.Count)
```
Comment (fedekunze) [inline rpc/backend/backend.go]: set the initial capacity to 0 and then use append. Otherwise, you might have empty items if the tx is not from the EVM module

File: rpc/namespaces/eth/api.go [hunk 11]
```diff
@@ -298,17 +323,39 @@ func (api *PublicEthereumAPI) GetBlockTransactionCountByHash(hash common.Hash) *
...
+	)
+	if blockNum != rpctypes.PendingBlockNumber {
+		if blockNum == rpctypes.LatestBlockNumber {
+			height, err = api.backend.LatestBlockNumber()
+			if err != nil {
+				return nil
+			}
+		} else {
+			height = blockNum.Int64()
+		}
```
Comment (fedekunze) [inline rpc/namespaces/eth/api.go]: this could be simplified with a switch statement

File: rpc/namespaces/eth/api.go (hunk 7 above)
Comment (fedekunze) [reply rpc/namespaces/eth/api.go]: number of pending txs queried from the mempool

File: rpc/namespaces/eth/api.go [hunk 12]
```diff
@@ -622,13 +742,41 @@ func (api *PublicEthereumAPI) GetTransactionByBlockHashAndIndex(hash common.Hash
...
+	)
+	if blockNum != rpctypes.PendingBlockNumber {
+		if blockNum == rpctypes.LatestBlockNumber {
+			height, err = api.backend.LatestBlockNumber()
+			if err != nil {
+				return nil, err
+			}
+		} else {
+			height = blockNum.Int64()
+		}
```
Comment (fedekunze) [inline rpc/namespaces/eth/api.go]: ditto switch

**Review by fedekunze — CHANGES_REQUESTED** [review]
haven't tested the changes yet but looks good overall!

File: rpc/namespaces/eth/api.go (hunk 7 above)
Comment (araskachoi) [reply rpc/namespaces/eth/api.go]: oof i was trying to copy the same value as `pendingTransactions` but missing a 0. Do you recommend something other than `1000` here?

File: tests-pending/rpc_pending_test.go [hunk 13]
```diff
@@ -0,0 +1,332 @@
...
+	param[0]["gasPrice"] = "0x1"
+
+	_ = util.Call(t, "eth_sendTransaction", param)
+
+	pendingNonce := util.GetNonce(t, "pending")
+	latestNonce := util.GetNonce(t, "latest")
+	t.Logf("Latest nonce is %d", latestNonce)
+	require.Equal(t, currentNonce, latestNonce)
+	t.Logf("Pending nonce is %d", pendingNonce)
+	require.NotEqual(t, latestNonce, pendingNonce)
```
Comment (noot) [inline tests-pending/rpc_pending_test.go]: maybe require pending = latest + 1?

File: tests-pending/rpc_pending_test.go [hunk 14]
```diff
@@ -0,0 +1,332 @@
...
+
+	require.Greater(t, uint64(pendingNonce), uint64(latestNonce))
+}
+
+func TestEth_Pending_GetBlockTransactionCountByNumber(t *testing.T) {
+	rpcRes := util.Call(t, "eth_getBlockTransactionCountByNumber", []interface{}{"pending"})
+	var preTxPendingTxCount hexutil.Uint
+	err := json.Unmarshal(rpcRes.Result, &preTxPendingTxCount)
+	require.NoError(t, err)
+	t.Logf("Pre tx pending nonce is %d", preTxPendingTxCount)
```
Comment (noot) [inline tests-pending/rpc_pending_test.go]: nonce -> tx count?

File: tests-pending/rpc_pending_test.go [hunk 15]
```diff
@@ -0,0 +1,332 @@
...
+	require.Equal(t, pendingBlock["blockNumber"], nil)
+	require.Equal(t, pendingBlock["transactionIndex"], nil)
+	require.NotEmpty(t, pendingBlock["hash"])
+
+	rpcRes = util.Call(t, "eth_getTransactionByBlockNumberAndIndex", []interface{}{"latest", "0x1"})
+	var latestBlock map[string]interface{}
+	err = json.Unmarshal(rpcRes.Result, &latestBlock)
+	require.NoError(t, err)
+
+	require.Empty(t, latestBlock)
```
Comment (noot) [inline tests-pending/rpc_pending_test.go]: I'm confused as to what's happening here, I thought `eth_getTransactionByBlockNumberAndIndex` returned a transaction

File: rpc/backend/backend.go (hunk 10 above)
Comment (araskachoi) [reply rpc/backend/backend.go]: yeah i remember this being an issue... but i just tested it without append and there seems to be no nil transactions inside the array anymore o.o

File: tests-pending/rpc_pending_test.go [hunk 16]
```diff
@@ -0,0 +1,332 @@
...
+	var pendingBlock map[string]interface{}
+	err = json.Unmarshal(rpcRes.Result, &pendingBlock)
+	require.NoError(t, err)
+
+	require.NotEmpty(t, pendingBlock)
+	require.Equal(t, nil, pendingBlock["blockHash"])
+	require.Equal(t, nil, pendingBlock["blockNumber"])
+	require.Equal(t, nil, pendingBlock["transactionIndex"])
+	require.NotEmpty(t, pendingBlock["hash"])
+	require.NotEmpty(t, pendingBlock["value"], "0xa")
```
Comment (noot) [inline tests-pending/rpc_pending_test.go]: same here, i thought `eth_getTransactionByHash` returned a transaction?

File: tests-pending/rpc_pending_test.go [hunk 17]
```diff
@@ -0,0 +1,332 @@
...
+	pendingNonce2 := util.GetNonce(t, "pending")
+	require.Greater(t, uint64(pendingNonce2), uint64(currNonce))
+	require.Greater(t, uint64(pendingNonce2), uint64(pendingNonce1))
+
+	// third transaction
+	param[0]["to"] = "0x7fb24493808b3f10527e3e0870afeb8a953052d2"
+	_ = util.Call(t, "eth_sendTransaction", param)
+	pendingNonce3 := util.GetNonce(t, "pending")
+	require.Greater(t, uint64(pendingNonce3), uint64(currNonce))
+	require.Greater(t, uint64(pendingNonce3), uint64(pendingNonce2))
```
Comment (noot) [inline tests-pending/rpc_pending_test.go]: maybe do checks for a hard value instead of just greater, same with above ie. pendingNonce3 == currNonce + 3

**Review by noot — COMMENTED** [review]
overall looks good, just some minor comments and questions about the tests

also, is it possible to put the pending tests into a subdirectory of `tests`?

File: tests-pending/rpc_pending_test.go (hunk 17 above)
Comment (araskachoi) [reply tests-pending/rpc_pending_test.go]: the problem with hard values is that there may be pending transactions leftover from previous tests... so unless there's a convenient way to flush the pending transaction queue or wait 150 sec for each test. I try to complete all the test within the same block because if a new block is produced in between, the test will fail

File: rpc/backend/backend.go (hunk 10 above)
Comment (noot) [reply rpc/backend/backend.go]: oh hmm was not aware of this

File: tests-pending/rpc_pending_test.go (hunk 13 above)
Comment (araskachoi) [reply tests-pending/rpc_pending_test.go]: there may be leftover pending transactions from the previous test /:

File: tests-pending/rpc_pending_test.go (hunk 15 above)
Comment (araskachoi) [reply tests-pending/rpc_pending_test.go]: we are checking for the returned transaction here. the check is a bit elementary and may need a more definitive check to make sure that the transaction exists

File: rpc/backend/backend.go (hunk 10 above)
Comment (fedekunze) [reply rpc/backend/backend.go]: did you try it without EVM transactions, for example a delegation, governance proposal or a bank transfer?

File: tests-pending/rpc_pending_test.go (hunk 14 above)
Comment (araskachoi) [reply tests-pending/rpc_pending_test.go]: i dont think those are the same things. the tx count that's in the block is less than that of the acct nonce. so we're trying to check for the block's pendingTx count

File: rpc/backend/backend.go [hunk 18]
```diff
@@ -209,10 +209,8 @@ func (b *EthermintBackend) PendingTransactions() ([]*rpctypes.Transaction, error
 		if err != nil {
 			return nil, err
 		}
-
-		transactions = append(transactions, rpcTx)
+		transactions[i] = rpcTx
```
Comment (fedekunze) [inline rpc/backend/backend.go]: revert to append

File: tests/tests-pending/rpc_pending_test.go [hunk 19]
```diff
@@ -0,0 +1,347 @@
...
+
+	// third transaction
+	param[0]["to"] = "0x7fb24493808b3f10527e3e0870afeb8a953052d2"
+	_ = util.Call(t, "eth_sendTransaction", param)
+	pendingNonce3 := util.GetNonce(t, "pending")
+	require.Greater(t, uint64(pendingNonce3), uint64(currNonce))
+	require.Greater(t, uint64(pendingNonce3), uint64(pendingNonce2))
+}
+
+// func TestEth_Call_Pending(t *testing.T) {
```
Comment (fedekunze) [inline tests/tests-pending/rpc_pending_test.go]: uncomment?

File: tests/utils.go [hunk 20]
```diff
@@ -0,0 +1,270 @@
...
+	param := []interface{}{hexutil.Bytes(from), block}
+	rpcRes := Call(t, "eth_getTransactionCount", param)
+
+	var nonce hexutil.Uint64
+	err = json.Unmarshal(rpcRes.Result, &nonce)
+	require.NoError(t, err)
+	return nonce
+}
+
+func UnlockAllAccounts(t *testing.T) bool {
```
Comment (fedekunze) [inline tests/utils.go]: no need to return a bool here
```suggestion
func UnlockAllAccounts(t *testing.T) {
```

File: tests/utils.go [hunk 21]
```diff
@@ -0,0 +1,270 @@
...
+	var accts []common.Address
+	rpcRes := Call(t, "eth_accounts", []map[string]string{})
+	err := json.Unmarshal(rpcRes.Result, &accts)
+	if err != nil {
+		return false
+	}
```
Comment (fedekunze) [inline tests/utils.go]:
```suggestion
	require.NoError(t, err)

```

File: tests/utils.go [hunk 22]
```diff
@@ -0,0 +1,270 @@
...
+	for _, acct := range accts {
+		fmt.Println("account: ", acct)
+		rpcRes = Call(t, "personal_unlockAccount", []interface{}{acct, ""})
+		var unlocked bool
+		err = json.Unmarshal(rpcRes.Result, &unlocked)
+		require.NoError(t, err)
+		require.True(t, unlocked)
+	}
+	return true
```
Comment (fedekunze) [inline tests/utils.go]:
```suggestion
```

File: tests/utils.go [hunk 23]
```diff
@@ -0,0 +1,270 @@
...
+
+	return nil
+}
+
+func GetNonce(t *testing.T, block string) hexutil.Uint64 {
+	from, err := GetAddress()
+	if err != nil {
+		fmt.Printf("failed to get account: %s\n", err)
+		os.Exit(1)
+	}
```
Comment (fedekunze) [inline tests/utils.go]: ditto require

File: tests/tests-pending/rpc_pending_test.go [hunk 24]
```diff
@@ -0,0 +1,347 @@
...
+	param := make([]map[string]string, 1)
+	param[0] = make(map[string]string)
+	param[0]["from"] = "0x" + fmt.Sprintf("%x", from)
+	param[0]["to"] = addrA
+	param[0]["value"] = "0xA"
+	param[0]["gasLimit"] = "0x5208"
+	param[0]["gasPrice"] = "0x1"
+	param[0]["data"] = data
+
+	_ = util.Call(t, "eth_sendTransaction", param)
```
Comment (fedekunze) [inline tests/tests-pending/rpc_pending_test.go]: should we check the response too here?

File: tests/tests-pending/rpc_pending_test.go [hunk 25]
```diff
@@ -0,0 +1,347 @@
...
+
+	param := make([]map[string]string, 1)
+	param[0] = make(map[string]string)
+	param[0]["from"] = "0x" + fmt.Sprintf("%x", from)
+	param[0]["to"] = addrA
+	param[0]["value"] = "0xA"
+	param[0]["gasLimit"] = "0x5208"
+	param[0]["gasPrice"] = "0x1"
+
+	_ = util.Call(t, "eth_sendTransaction", param)
```
Comment (fedekunze) [inline tests/tests-pending/rpc_pending_test.go]: ditto

File: tests/tests-pending/rpc_pending_test.go [hunk 26]
```diff
@@ -0,0 +1,347 @@
...
```
Comment (fedekunze) [inline tests/tests-pending/rpc_pending_test.go]: ditto

**Review by fedekunze — COMMENTED** [review]
Few comments. Do you have some instructions to test against any of the Eth tooling like metamask, etc (maybe @noot)?

**Comment by fedekunze** [comment]
also, can you add a `Feature` changelog entry?

File: rpc/backend/backend.go (hunk 10 above)
Comment (noot) [reply rpc/backend/backend.go]: i agree this needs to be changed back to append

File: tests/tests-pending/rpc_pending_test.go [hunk 27]
```diff
@@ -0,0 +1,347 @@
...
+	param[0]["to"] = addrA
+	param[0]["value"] = "0xA"
+	param[0]["gasLimit"] = "0x5208"
+	param[0]["gasPrice"] = "0x1"
+	param[0]["data"] = data
+
+	_ = util.Call(t, "eth_sendTransaction", param)
+
+	rpcRes := util.Call(t, "eth_getTransactionByBlockNumberAndIndex", []interface{}{"pending", "0x" + fmt.Sprintf("%X", pendingTxCount)})
+	var pendingBlock map[string]interface{}
```
Comment (noot) [inline tests/tests-pending/rpc_pending_test.go]: rename to `pendingTx`?

File: tests/tests-pending/rpc_pending_test.go [hunk 28]
```diff
@@ -0,0 +1,347 @@
...
+	param[0]["gasPrice"] = "0x1"
+	param[0]["data"] = data
+
+	txRes := util.Call(t, "eth_sendTransaction", param)
+	var txHash common.Hash
+	err := txHash.UnmarshalJSON(txRes.Result)
+	require.NoError(t, err)
+
+	rpcRes := util.Call(t, "eth_getTransactionByHash", []interface{}{txHash})
+	var pendingBlock map[string]interface{}
```
Comment (noot) [inline tests/tests-pending/rpc_pending_test.go]: same here

File: tests/utils.go (hunk 20 above)
Comment (araskachoi) [reply tests/utils.go]: then i will return `error`. that sounds okay?

File: tests-pending/rpc_pending_test.go (hunk 16 above)
Comment (araskachoi) [reply tests-pending/rpc_pending_test.go]: does this look okay now?

File: tests/tests-pending/rpc_pending_test.go (hunk 19 above)
Comment (araskachoi) [reply tests/tests-pending/rpc_pending_test.go]: we have not implmented any pending queries to `Call` because we do not have access to any contract pending states. will just remove!

File: tests/utils.go (hunk 20 above)
Comment (araskachoi) [reply tests/utils.go]: nvm i see your suggested changes!

File: CHANGELOG.md [hunk 29]
```diff
@@ -176,6 +176,15 @@ corresponding Ethereum API namespace:
   * `eth_getLogs` and `eth_getFilterChanges` for log filters use the same underlying method as `eth_getFilterLogs`
   * update `HandleMsgEthereumTx` to store logs using the ethereum hash
 * (app) [\#187](https://github.com/cosmos/ethermint/issues/187) Add support for simulations.
+* (rpc) [\#571](https://github.com/cosmos/ethermint/pull/571) Add pending queries to rpc calls. This allows for the querying of pending transactions and other relevant information that pertains to the pending state.
```
Comment (fedekunze) [inline CHANGELOG.md]: This needs to go under the `Unreleased` section

File: tests/tests-pending/rpc_pending_test.go [hunk 30]
```diff
@@ -0,0 +1,326 @@
...
+
+	param := make([]map[string]string, 1)
+	param[0] = make(map[string]string)
+	param[0]["from"] = "0x" + fmt.Sprintf("%x", from)
+	param[0]["to"] = addrA
+	param[0]["value"] = "0xA"
+	param[0]["gasLimit"] = "0x5208"
+	param[0]["gasPrice"] = "0x1"
+
+	_ = util.Call(t, "eth_sendTransaction", param)
```
Comment (fedekunze) [inline tests/tests-pending/rpc_pending_test.go]:
```suggestion
	rpcRes = util.Call(t, "eth_sendTransaction", param)
	require.Nil(t, rpcRes.Error)
```

File: CHANGELOG.md (hunk 29 above)
Comment (araskachoi) [reply CHANGELOG.md]: done!

**Review by noot — APPROVED** [review]

File: tests/tests-pending/rpc_pending_test.go [hunk 31]
```diff
@@ -0,0 +1,326 @@
...
+	err = res.UnmarshalJSON(rpcRes.Result)
+	require.NoError(t, err)
+	postTxLatestBalance := res.ToInt()
+	t.Logf("Got latest balance %s for %s post tx\n", postTxLatestBalance, addrA)
+
+	require.Equal(t, preTxLatestBalance, postTxLatestBalance)
+	// 1 if x > y; where x is postTxPendingBalance, y is preTxPendingBalance
+	if postTxLatestBalance.Cmp(preTxPendingBalance) != 0 {
+		t.Errorf("expected balance: %d, got: %s", 0, res.String())
+	}
```
Comment (fedekunze) [inline tests/tests-pending/rpc_pending_test.go]: this check is not necessary because it's already checked on the line above. Unless you want to compare against `0` (which is what the log states?)

File: tests/utils.go [hunk 32]
```diff
@@ -0,0 +1,265 @@
...
+}
+
+func UnlockAllAccounts(t *testing.T) {
+	var accts []common.Address
+	rpcRes := Call(t, "eth_accounts", []map[string]string{})
+	err := json.Unmarshal(rpcRes.Result, &accts)
+	require.NoError(t, err)
+
+	for _, acct := range accts {
+		fmt.Println("account: ", acct)
```
Comment (fedekunze) [inline tests/utils.go]:
```suggestion
		t.Logf("account: %v", acct)
```

**Review by fedekunze — COMMENTED** [review]
few minor comments

File: tests/tests-pending/rpc_pending_test.go (hunk 31 above)
Comment (araskachoi) [reply tests/tests-pending/rpc_pending_test.go]: absolutely correct. removing

**Review by fedekunze — APPROVED** [review]
Great work! 👍

File: rpc/namespaces/eth/api.go [hunk 33]
```diff
@@ -513,17 +580,29 @@ func (api *PublicEthereumAPI) doCall(
...
+	var msgs []sdk.Msg
 	// Create new call message
 	msg := evmtypes.NewMsgEthermint(0, &toAddr, sdk.NewIntFromBigInt(value), gas,
 		sdk.NewIntFromBigInt(gasPrice), data, sdk.AccAddress(addr.Bytes()))
+	msgs = append(msgs, msg)
 
-	if err := msg.ValidateBasic(); err != nil {
-		return nil, err
+	// convert the pending transactions into ethermint msgs
+	if blockNum == rpctypes.PendingBlockNumber {
```
Comment (summerpro) [inline rpc/namespaces/eth/api.go:590]: Why is the pending transaction put in here? My understanding is that only the execution result of one transaction is needed here

File: rpc/namespaces/eth/api.go [hunk 34]
```diff
@@ -571,14 +650,71 @@ func (api *PublicEthereumAPI) GetBlockByHash(hash common.Hash, fullTx bool) (map
...
+	}
+
+	// latest block info
+	latestBlock, err := api.clientCtx.Client.Block(&height)
+	if err != nil {
+		return nil, err
+	}
+
+	// number of pending txs queried from the mempool
+	unconfirmedTxs, err := api.clientCtx.Client.UnconfirmedTxs(1000)
```
Comment (summerpro) [inline rpc/namespaces/eth/api.go:670]: What if the actual tx quantity is more than 1000?

Comment (fedekunze) [reply rpc/namespaces/eth/api.go:670]: It's highly unlikely (for now) as on the Cosmos Hub there are 1 or 2 avg txs per block.
