### PR TITLE
Reset cache after csdb committed

### LINKED ISSUE #674: panic with "wrong Block.Header.AppHash" when a restarted node calling AddLog
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__
Reproduce every time
1. [First Step]
Deploy 4 node with ethermintd
2. [Second Step]
Publish some contract and call it on ethermint 
3. [and so on...]
Restart one of nodes
__Expected behavior:__ 
Node runs well
__Actual behavior:__ 
panic "wrong Block.Header.AppHash" happened
__Additional info:__ 
here is reference of csdb.logSize, if it not store to db, every new node will set it to zero, but for running node, csdb.logSize may not be zero, that's a difference between keep running node and restart node
https://github.com/cosmos/ethermint/blob/9659b81ee1bf27f979b5f0793778ff97e2fc62b6/x/evm/types/statedb.go#L213

### PR DESCRIPTION
**Pull request by KamiD**
Closes: #674 

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

File: x/evm/keeper/abci.go [hunk 1]
```diff
@@ -44,14 +44,15 @@ func (k Keeper) EndBlock(ctx sdk.Context, req abci.RequestEndBlock) []abci.Valid
...
 
+	root, err := k.Commit(ctx, true)
 	// Commit state objects to KV store
-	if _, err := k.Commit(ctx, true); err != nil {
+	if err != nil {
 		k.Logger(ctx).Error("failed to commit state objects", "error", err, "height", ctx.BlockHeight())
 		panic(err)
 	}
 
 	// Clear accounts cache after account data has been committed
```
Comment (fedekunze) [inline x/evm/keeper/abci.go]: can you update the comment?

File: x/evm/keeper/abci.go [hunk 2]
```diff
@@ -44,14 +44,15 @@ func (k Keeper) EndBlock(ctx sdk.Context, req abci.RequestEndBlock) []abci.Valid
...
-	k.ClearStateObjects(ctx)
+	k.Reset(ctx, root)
```
Comment (fedekunze) [inline x/evm/keeper/abci.go]:
```suggestion
	if err := k.Reset(ctx, root); err != nil {
		panic(err)
	}
```

**Review by fedekunze — COMMENTED** [review]
Looks good. Can you add a bugfix entry on the CHANGELOG.md?

**Review by fedekunze — APPROVED** [review]
