### PR TITLE
deploy network and contract

### LINKED ISSUE #390: Integration test deploy contract
__Current behavior:__ [What currently happens]

In order to test a contract deployment, one has to manually deploy it using web3.

__Desired behavior:__ [What you would like to happen]

- Integrate the [ethermint-deploy](https://github.com/ChainSafe/ethermint-deploy) repository into Ethermint
- Create an integration test (possibly in JS) that checks if the counter contract deployment succeeds.
- Add the test to GitHub Actions workflow

__Use case:__ [Why is this important (helps with prioritizing requests)]

Test if anything is broken when new changes are introduced.

### PR DESCRIPTION
**Pull request by araskachoi**
Requires the user to have solc and npm installed on the system.

Run `make test-contract`
this will
- deploy the network
- add an account to genesis
- compile the `counter.sol` contract
- deploy using the genesis account
- check if the transaction was committed to the evm

Closes: https://github.com/ChainSafe/ethermint/issues/390

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

File: scripts/contract-test.sh [hunk 1]
```diff
@@ -0,0 +1,66 @@
+#!/bin/bash
+
+FKEY="faucet"
+TESTKEY="test"
+
+CHAINID=123
+MONIKER="localbenchmarktestnet"
+
+# remove existing daemon and client
+rm -rf ~/.emint*
```
Comment (fedekunze) [inline scripts/contract-test.sh]: I don't think we want to remove the existing blockchain data?

File: Makefile [hunk 2]
```diff
@@ -167,6 +167,20 @@ docker:
 .PHONY: build install update-tools tools godocs clean format lint \
 test-cli test-race test-unit test test-import
 
+test-contract:
+	env GOBIN= go get -u golang.org/x/tools/cmd/stringer
+	env GOBIN= go get -u github.com/kevinburke/go-bindata/go-bindata
+	env GOBIN= go get -u github.com/fjl/gencodec
+	env GOBIN= go get -u github.com/golang/protobuf/protoc-gen-go
+	env GOBIN= go install ./cmd/abigen
```
Comment (fedekunze) [inline Makefile]: can we move these to `make tools`?

Comment (fedekunze) [reply Makefile]: you can also use `$(GOBIN)` instead of `env GOBIN=`

File: Makefile [hunk 3]
```diff
@@ -167,6 +167,20 @@ docker:
...
+	@type "npm" 2> /dev/null || echo 'Please install node.js and npm'
+	@type "solc" 2> /dev/null || echo 'Please install solc'
+	@type "protoc" 2> /dev/null || echo 'Please install protoc'
```
Comment (fedekunze) [inline Makefile]: I don't think it exits if the user hasn't installed the tools?

File: cmd/abigen/main.go [hunk 4]
```diff
@@ -0,0 +1,278 @@
...
+	if err := ioutil.WriteFile(c.GlobalString(outFlag.Name), []byte(code), 0600); err != nil {
+		utils.Fatalf("Failed to write ABI binding: %v", err)
+	}
+	return nil
+}
+
+func main() {
+	log.Root().SetHandler(log.LvlFilterHandler(log.LvlInfo, log.StreamHandler(os.Stderr, log.TerminalFormat(true))))
+
+	if err := app.Run(os.Args); err != nil {
```
Comment (fedekunze) [inline cmd/abigen/main.go]: what is this file for?

File: scripts/contract-test.sh [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+# Start the node (remove the --pruning=nothing flag if historical queries are not needed) in background and log to emintd.log
+emintd start --pruning=nothing --rpc.unsafe --log_level "main:info,state:info,mempool:info" --trace > emintd.log &
+
+sleep 1
+
+# Start the rest server with unlocked faucet key in background and log to emintcli.log 
+emintcli rest-server --laddr "tcp://localhost:8545" --unlock-key $FKEY --chain-id $CHAINID --trace > emintcli.log &
+
+solc --abi contracts/counter.sol --bin -o contracts/abi_bin
+abigen --bin=contracts/abi_bin/contracts_counter_sol_Counter.bin --abi=contracts/abi_bin/contracts_counter_sol_Counter.abi --pkg=counter --out=counter.go
```
Comment (fedekunze) [inline scripts/contract-test.sh]: so I was originally thinking if we could use existing geth functionality to deploy a contract using plain Go, like this contract:

https://github.com/ethereum/go-ethereum/blob/9e88224eb86c92c78f5f03ffcd0793704a8b4309/contracts/checkpointoracle/contract/oracle.go#L35-L46

**Review by fedekunze — COMMENTED** [review]
Generally looks good. Ideally, we should add a GitHub Action workflow to test this on every PR

File: scripts/contract-test.sh (hunk 1 above)
Comment (araskachoi) [reply scripts/contract-test.sh]: then is it okay to append previous test logs? If so, i'll remove!

File: Makefile (hunk 2 above)
Comment (araskachoi) [reply Makefile]: :+1: will do

File: cmd/abigen/main.go (hunk 4 above)
Comment (araskachoi) [reply cmd/abigen/main.go]: this creates the binary for `abigen` in `env GOBIN= go install ./cmd/abigen` (line 175)

File: Makefile (hunk 3 above)
Comment (araskachoi) [reply Makefile]: correct... these will need to be installed via package manager (apt-get, apk, etc.) any tips? i thought that this would just prompt user to install these using their desired package manager. 
I have a compatible dokcker file for testing this internally as these tools arent necessary for running the client. Any comments on this?

Comment (fedekunze) [reply Makefile]: maybe use `exit 1` after each `echo`?

Comment (araskachoi) [reply Makefile]: i did that, you are a literal mind reader

File: cmd/abigen/main.go (hunk 4 above)
Comment (fedekunze) [reply cmd/abigen/main.go]: q: is it possible to replace it with the go code below?

Comment (araskachoi) [reply cmd/abigen/main.go]: the go code below (the link you had sent in below comment) is generated by `abigen`. So will need this to deploy contract through go

File: scripts/contract-test.sh (hunk 5 above)
Comment (araskachoi) [reply scripts/contract-test.sh]: will look into this, should be doable

File: contracts/counter/main.go [hunk 6]
```diff
@@ -0,0 +1,60 @@
...
+
+func main() {
+	client, err := ethclient.Dial("http://localhost:8545")
+	if err != nil {
+		log.Fatal(err)
+	}
+
+	// replace with os.Args[1]
+	// privateKey, err := crypto.HexToECDSA(os.Args[1])
+	privateKey, err := crypto.HexToECDSA("fad9c8855b740a0b7ed4c221dbad0f33a83a49cad6b3fe8d5817ac83d38b6a19")
```
Comment (noot) [inline contracts/counter/main.go]: should this be updated here?

Comment (araskachoi) [reply contracts/counter/main.go]: yeah, changed to a draft but will get back on this!

File: cmd/abigen/main.go (hunk 4 above)
Comment (fedekunze) [reply cmd/abigen/main.go]: or maybe use `geth abigen`? I'm sceptic of adding a dependency that we will have to maintain and constantly check if it's not deprecated.

Comment (araskachoi) [reply cmd/abigen/main.go]: done with commit 45d88f3

**Comment by araskachoi** [comment]
This still requires a valid private key to send and sign the transactions. Currently, using the private key provided by `emintcli keys unsafe-export-eth-export` gives an error in ethermint with the err msg:
```
I[2020-07-27|23:00:18.053] Rejected bad transaction                     module=mempool tx=BC20E6CF4AFDF2AB5DB35C1FD065081C89169CF8617662351B17BD53F6492E5D peerID= res="&{CheckTx:code:4 log:\"signature verification failed: invalid signature: unauthorized\" codespace:\"sdk\" }" err=null
```

File: Makefile [hunk 7]
```diff
@@ -217,6 +253,13 @@ test-import:
 test-rpc:
 	./scripts/integration-test-all.sh -q 1 -z 1 -s 2
 
+test-contract:
+	@type "npm" 2> /dev/null || (echo 'Npm does not exist. Please install node.js and npm."' && exit 1)
+	@type "solcjs" 2> /dev/null || (echo 'Solc does not exist. Please install solc."' && exit 1)
```
Comment (fedekunze) [inline Makefile]: so according to the [solc](https://www.npmjs.com/package/solc) package, it installs `solcjs`? but the contract requires `solc`? I'm a bit confused by that

File: contracts/counter/counter.sol [hunk 8]
```diff
@@ -0,0 +1,17 @@
+pragma solidity >=0.5.11;
+
+contract Counter {
```
Comment (fedekunze) [inline contracts/counter/counter.sol]: can we delete this contract and use the one available on `tests-solidity/suites/basic/contract/Counter.sol`?

**Review by fedekunze — COMMENTED** [review]
I added a few changes. I can't get `make test-contract` to work:

```
File at /Users/federico/.ethermintd/config/genesis.json is a valid genesis file
panic: invalid coin denomination: failed to execute message; message index: 0

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/genutil.DeliverGenTxs(0x5463360, 0xc00019e008, 0x5474200, 0xc0001bd380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/federico/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/x/genutil/gentx.go:102 +0x328
github.com/cosmos/cosmos-sdk/x/genutil.InitGenesis(...)
	/Users/federico/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/x/genutil/genesis.go:19
github.com/cosmos/cosmos-sdk/x/genutil.AppModule.InitGenesis(0x545e6a0, 0xc000e0a540, 0x5440300, 0xc00014c510, 0xc000236220, 0x5463360, 0xc00019e008, 0x5474200, 0xc0001bd380, 0x0, ...)
	/Users/federico/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/x/genutil/module.go:88 +0x170
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc000e0a9a0, 0x5463360, 0xc00019e008, 0x5474200, 0xc0001bd380, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/federico/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/types/module/module.go:265 +0x295
github.com/cosmos/ethermint/app.(*EthermintApp).InitChainer(0xc0001d3b80, 0x5463360, 0xc00019e008, 0x5474200, 0xc0001bd380, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/federico/ethermint/app/ethermint.go:344 +0x125
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000153cc0, 0x309f47e8, 0xed6e2f87c, 0x0, 0xc000121c48, 0x6, 0xc0001bd280, 0x5cfcf08, 0x0, 0x0, ...)
	/Users/federico/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/baseapp/abci.go:39 +0x2fb
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc00040d320, 0x309f47e8, 0xed6e2f87c, 0x0, 0xc000121c48, 0x6, 0xc0001bd280, 0x5cfcf08, 0x0, 0x0, ...)
	/Users/federico/go/pkg/mod/github.com/tendermint/tendermint@v0.33.7/abci/client/local_client.go:223 +0xf8
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc000237f50, 0x309f47e8, 0xed6e2f87c, 0x0, 0xc000121c48, 0x6, 0xc0001bd280, 0x5cfcf08, 0x0, 0x0, ...)
	/Users/federico/go/pkg/mod/github.com/tendermint/tendermint@v0.33.7/proxy/app_conn.go:65 +0x75
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000eb9080, 0xa, 0x0, 0x51130db, 0x6, 0xc000121c48, 0x6, 0x0, 0x0, 0x0, ...)
	/Users/federico/go/pkg/mod/github.com/tendermint/tendermint@v0.33.7/consensus/replay.go:319 +0x6d6
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000eb9080, 0x5476700, 0xc000238080, 0x65a5108, 0x18)
	/Users/federico/go/pkg/mod/github.com/tendermint/tendermint@v0.33.7/consensus/replay.go:269 +0x4bc
github.com/tendermint/tendermint/node.doHandshake(0x5475b80, 0xc00012e770, 0xa, 0x0, 0x51130db, 0x6, 0xc000121c48, 0x6, 0x0, 0x0, ...)
	/Users/federico/go/pkg/mod/github.com/tendermint/tendermint@v0.33.7/node/node.go:264 +0x19b
github.com/tendermint/tendermint/node.NewNode(0xc0011fc640, 0x545cd60, 0xc000e07680, 0xc000236710, 0x543ea80, 0xc000243c40, 0xc000236940, 0x52cac20, 0xc000236950, 0x5463ea0, ...)
	/Users/federico/go/pkg/mod/github.com/tendermint/tendermint@v0.33.7/node/node.go:587 +0x356
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc0011b3180, 0x52cc3d8, 0x1d, 0x0, 0x0)
	/Users/federico/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/server/start.go:180 +0x4ca
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00120a580, 0xc0011f8870, 0x0, 0x5, 0x0, 0x0)
	/Users/federico/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/server/start.go:82 +0xb4
github.com/spf13/cobra.(*Command).execute(0xc00120a580, 0xc0011f8820, 0x5, 0x5, 0xc00120a580, 0xc0011f8820)
	/Users/federico/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001d18c0, 0x513eee0, 0xc0011cbe60, 0x41920e6)
	/Users/federico/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/federico/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0001d18c0, 0x52cc808, 0x511ed0c, 0x10)
	/Users/federico/go/pkg/mod/github.com/tendermint/tendermint@v0.33.7/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/federico/ethermint/cmd/ethermintd/main.go:91 +0x5c5
scripts/contract-test.sh: line 58: solc: command not found
mv: rename contracts/counter/contracts_counter_counter_sol_Counter.abi to contracts/counter/counter_sol.abi: No such file or directory
mv: rename contracts/counter/contracts_counter_counter_sol_Counter.bin to contracts/counter/counter_sol.bin: No such file or directory
panic: dial tcp [::1]:26657: connect: connection refused

goroutine 1 [running]:
github.com/cosmos/ethermint/rpc.NewPublicFilterAPI(0x0, 0x0, 0x0, 0x521fdc0, 0xc0011dd6b0, 0x7ffeefbff9b4, 0x6, 0x0, 0x0, 0x51eb5a0, ...)
	/Users/federico/ethermint/rpc/filter_api.go:62 +0x1a6
github.com/cosmos/ethermint/rpc.GetRPCAPIs(0x0, 0x0, 0x0, 0x521fdc0, 0xc0011dd6b0, 0x7ffeefbff9b4, 0x6, 0x0, 0x0, 0x51eb5a0, ...)
	/Users/federico/ethermint/rpc/apis.go:49 +0x217
github.com/cosmos/ethermint/rpc.registerRoutes(0xc00139a120)
	/Users/federico/ethermint/rpc/config.go:73 +0x150
github.com/cosmos/cosmos-sdk/client/lcd.ServeCommand.func1(0xc0011f4b00, 0xc000251dc0, 0x0, 0x7, 0x0, 0x0)
	/Users/federico/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/client/lcd/root.go:91 +0x5d
github.com/spf13/cobra.(*Command).execute(0xc0011f4b00, 0xc000251d50, 0x7, 0x7, 0xc0011f4b00, 0xc000251d50)
	/Users/federico/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc001198000, 0x4506745, 0xc001198000, 0x4e9ecb1)
	/Users/federico/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/federico/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc001198000, 0x50c7950, 0x2, 0xc0010c8300)
	/Users/federico/go/pkg/mod/github.com/tendermint/tendermint@v0.33.7/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/federico/ethermint/cmd/ethermintcli/main.go:80 +0x405
Fatal: Failed to read input ABI: open contracts/counter/counter_sol.abi: no such file or directory
sed: 1: "contracts/counter/count ...": command c expects \ followed by text

curl: (7) Failed to connect to localhost port 8545: Connection refused
363D1FC813FB73DC6490CA44A1BAAC79B38FD3CAD0BA9D13201608846533D2D2
2020/09/03 16:45:20 open /ethermint/contracts/counter/counter_sol.bin: no such file or directory
make: *** [test-contract] Error 1
```

File: Makefile (hunk 7 above)
Comment (araskachoi) [reply Makefile:258]: very confused why you still have that 
Screen Shot 2020-09-03 at 9 33 18 AM

Comment (araskachoi) [reply Makefile:258]: oof, i think something happened and it reverted back to the "old" files.

**Comment by araskachoi** [comment]
omybejeez... finally got the test work work!

File: .github/workflows/deploy-contract.yml [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/setup-go@v2.1.2
+      - name: install runsim
+        run: |
+          export GO111MODULE="on" && go get github.com/cosmos/tools/cmd/runsim@v1.0.0
+      - uses: actions/cache@v2.1.1
+        with:
+          path: ~/go/bin
+          key: ${{ runner.os }}-go-runsim-binary
```
Comment (fedekunze) [inline .github/workflows/deploy-contract.yml]: not sure why we need to install runsim? seems unrelated

File: Dockerfile [hunk 10]
```diff
@@ -6,26 +6,26 @@ ENV PACKAGES git build-base
 # Set working directory for the build
 WORKDIR /go/src/github.com/Chainsafe/ethermint
 
-# Install dependencies
-RUN apk add --update $PACKAGES
-RUN apk add linux-headers
+# Install dependencies
```
Comment (fedekunze) [inline Dockerfile]: can you cleanup the spaces 🙏

File: .github/workflows/deploy-contract.yml (hunk 9 above)
Comment (araskachoi) [reply .github/workflows/deploy-contract.yml]: haha woops i was using that as a reference but accidentally pushed!

**Review by fedekunze — APPROVED** [review]
