### PR TITLE
fix lint issues reported by golangci #260

### LINKED ISSUE #260: fix lint issues reported by golangci
```
golangci-lint run -c .golangci.yml --deadline=5m
x/evm/handler.go:79:51: unslice: could simplify txHash[:] to txHash (gocritic)
        err = k.SetTransactionLogs(ctx, returnData.Logs, txHash[:])
                                                         ^
x/evm/types/msg.go:40:3: `hash` is unused (structcheck)
                hash atomic.Value
                ^
app/ante/eth.go:140:57: S1039: unnecessary use of fmt.Sprintf (gosimple)
                return ctx, sdkerrors.Wrap(sdkerrors.ErrUnauthorized, fmt.Sprintf("signature verification failed"))
```

### PR DESCRIPTION
**Pull request by thomasmodeneis**
Closes: #260

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

File: x/evm/types/msg.go [hunk 1]
```diff
@@ -37,7 +37,6 @@ type (
 		Data TxData
 
 		// caches
-		hash atomic.Value
```
Comment (fedekunze) [inline x/evm/types/msg.go:40]: hmmm what's the lint error here? afaik this should be used

Comment (fedekunze) [reply x/evm/types/msg.go:40]: cc @noot ^^

Comment (thomasmodeneis) [reply x/evm/types/msg.go:40]:
```
x/evm/types/msg.go:40:3: `hash` is unused (structcheck)
                hash atomic.Value
```

Comment (noot) [reply x/evm/types/msg.go:40]: not sure about this one, I didn't write this part. i think since Austin removed the hash function for this type it's unused now?

**Review by noot — APPROVED** [review]

File: x/evm/types/msg.go (hunk 1 above)
Comment (thomasmodeneis) [reply x/evm/types/msg.go:40]: we can always revert it back if something breaks.

Comment (austinabell) [reply x/evm/types/msg.go:40]: yeah there is no need for it currently because you need to know the tx encoding protocol to hash, so this hash isn't cached, but it can definitely be changed to do so (might be worth it later)

Comment (austinabell) [reply x/evm/types/msg.go:40]: my bad I didn't think to remove this, was just a quick fix before, but can add a utility function to hash only if cached hash not set (I indicated this as being ideal, but not a priority, but might be good to at least leave a TODO)
