### PR TITLE
Modified the init.sh script

### LINKED ISSUE #238: Running the init.sh script a second time will cause key errors
__System info:__
commit da9157e406177b0994542dbf6e2440b218ec95b9
MacOS
Trying to create a local ethermint blockchain for testing, dev, etc

__Steps to reproduce:__

1. run ./init.sh  the first time with no issues
2.  run ./init.sh again to reset/reinitialize the chain
3. deploy a smart contract to the system using either [ethermint-scripts](https://github.com/chainsafe/ethermint-scripts) or [ethermint-deploy](https://github.com/chainsafe/ethermint-deploy)

__Expected behavior:__ Contract to deploy

__Actual behavior:__ 
`{"codespace":"sdk","code":4,"message":"signature verification failed: invalid signature"}`

__Additional info:__ 
I believe this has something to do with trying to add the key **mykey** every time in the script

### PR DESCRIPTION
**Pull request by letterj**
Changed the removal lines to removed everything using a wildcard
Changed the the common parameters into variables

Fixes #238

Closes: #238 

## Description
Updated the init.sh script that generates an ethermint blockchain locally for dev and test.  

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

File: init.sh [hunk 1]
```diff
@@ -1,32 +1,44 @@
 #!/bin/bash
-rm -rf ~/.emintcli
-rm -rf ~/.emintd
```
Comment (noot) [inline init.sh:3]: what does this do?

**Review by noot — APPROVED** [review]
works for me!

File: init.sh (hunk 1 above)
Comment (fedekunze) [reply init.sh:3]: removes the existing binary

**Review by fedekunze — APPROVED** [review]
