### PR TITLE
fix incorrect blockHash in evm

### LINKED ISSUE #775: MisUse of headHash as blockHash when create EVM context
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

When Create EVM, we will pass a getHash function to the evm context:
```
func (st StateTransition) newEVM(
	ctx sdk.Context,
	csdb *CommitStateDB,
	gasLimit uint64,
	gasPrice *big.Int,
	config ChainConfig,
	extraEIPs []int,
) *vm.EVM {
	// Create context for evm
	blockCtx := vm.BlockContext{
		CanTransfer: core.CanTransfer,
		Transfer:    core.Transfer,
		GetHash:     GetHashFn(ctx, csdb),
		Coinbase:    common.Address{}, // there's no beneficiary since we're not mining
		BlockNumber: big.NewInt(ctx.BlockHeight()),
		Time:        big.NewInt(ctx.BlockHeader().Time.Unix()),
		Difficulty:  big.NewInt(0), // unused. Only required in PoW context
		GasLimit:    gasLimit,
	}
        ...
}
```
in the GetHashFn，when the require height is the current block height, it will return the current Block's head hash, but not the blockHash
```
// GetHashFn implements vm.GetHashFunc for Ethermint. It handles 3 cases:
//  1. The requested height matches the current height from context (and thus same epoch number)
//  2. The requested height is from an previous height from the same chain epoch
//  3. The requested height is from a height greater than the latest one
func GetHashFn(ctx sdk.Context, csdb *CommitStateDB) vm.GetHashFunc {
	return func(height uint64) common.Hash {
		switch {
		case ctx.BlockHeight() == int64(height):
			// Case 1: The requested height matches the one from the context so we can retrieve the header
			// hash directly from the context.
			return HashFromContext(ctx)

		case ctx.BlockHeight() > int64(height):
			// Case 2: if the chain is not the current height we need to retrieve the hash from the store for the
			// current chain epoch. This only applies if the current height is greater than the requested height.
			return csdb.WithContext(ctx).GetHeightHash(height)

		default:
			// Case 3: heights greater than the current one returns an empty hash.
			return common.Hash{}
		}
	}
}
```
this would lead to something  wrong for we can only get the block detail with blockHash, not headHash.

__Steps to reproduce:__

1. [First Step]
2. [Second Step]
3. [and so on...]

__Expected behavior:__ [What you expected to happen]

always return BlockHash, not HeadHash

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]

### PR DESCRIPTION
**Pull request by summerpro**
Closes: #775 

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

File: x/evm/keeper/abci.go [hunk 1]
```diff
@@ -22,11 +22,12 @@ func (k *Keeper) BeginBlock(ctx sdk.Context, req abci.RequestBeginBlock) {
 	ctx = ctx.WithGasMeter(sdk.NewInfiniteGasMeter())
 
 	// Set the hash -> height and height -> hash mapping.
-	hash := req.Header.LastBlockId.GetHash()
-	height := req.Header.GetHeight() - 1
+	hash := req.Hash
+	height := req.Header.GetHeight()
```
Comment (noot) [inline x/evm/keeper/abci.go]: this should stay as it was before, the reason we are setting the hash for the previous block is because the block hash for the current height has not yet been determined (as we are just beginning the block).

Comment (summerpro) [reply x/evm/keeper/abci.go]: 1. But we found that "req.Hash" is the block hash of the current height. By this hash, you can go to the api "func (api *PublicEthereumAPI) GetBlockByHash" to successfully query the block information
2. Maybe the calculation of block hash only needs transaction and does not need the calculation result of transaction. Therefore, before beginBlock, the consensus of the block has ended, and the block hash is already determined

**Comment by zhongqiuwood** [comment]
The PR fixed:
The solidity globally Variable [blockhash] does not work
```
blockhash(uint blockNumber) returns (bytes32): hash of the given block - only works for 256 most recent, excluding current, blocks
```

File: x/evm/types/state_transition.go [hunk 2]
```diff
@@ -57,7 +57,7 @@ func GetHashFn(ctx sdk.Context, csdb *CommitStateDB) vm.GetHashFunc {
 		case ctx.BlockHeight() == int64(height):
 			// Case 1: The requested height matches the one from the context so we can retrieve the header
 			// hash directly from the context.
-			return HashFromContext(ctx)
+			return csdb.bhash
```
Comment (noot) [inline x/evm/types/state_transition.go]: update comment

Comment (araskachoi) [reply x/evm/types/state_transition.go]: @zhongqiuwood @summerpro  can we get a quick update so that we can merge? sorry for the late response!

Comment (summerpro) [reply x/evm/types/state_transition.go]: @araskachoi @noot  updated

**Review by noot — APPROVED** [review]

File: x/evm/keeper/abci.go [hunk 3]
```diff
@@ -22,11 +22,12 @@ func (k *Keeper) BeginBlock(ctx sdk.Context, req abci.RequestBeginBlock) {
 	ctx = ctx.WithGasMeter(sdk.NewInfiniteGasMeter())
 
 	// Set the hash -> height and height -> hash mapping.
-	hash := req.Header.LastBlockId.GetHash()
-	height := req.Header.GetHeight() - 1
```
Comment (araskachoi) [inline x/evm/keeper/abci.go:26]: why do we not "- 1" the blockheight anymore? has the GetHeight() method changed?

File: x/evm/types/state_transition.go [hunk 4]
```diff
@@ -268,21 +268,3 @@ func (st StateTransition) TransitionDb(ctx sdk.Context, config ChainConfig) (*Ex
...
-	tmBlockHash := tmHeader.Hash()
-
-	// NOTE: if the validator set hash is missing the hash will be returned as nil,
-	// so we need to check for this case to prevent a panic when calling Bytes()
-	if tmBlockHash == nil {
-		return common.Hash{}
-	}
-
-	return common.BytesToHash(tmBlockHash.Bytes())
-}
```
Comment (araskachoi) [inline x/evm/types/state_transition.go:288]: are we removing this because the return of `GetHashFn` is compatible with tendermint msgs?

File: x/evm/keeper/abci.go (hunk 3 above)
Comment (summerpro) [reply x/evm/keeper/abci.go:26]: 1. The code before modification thinks:
In the beginBlock stage of "height n", only the block hash of "height n-1" can be obtained, but the block hash of "height n" cannot be obtained.

2. Now we find:
In the beginBlock stage of "height n", not only the block hash of "height n-1" can be obtained, but also the block hash of "height n" can be obtained.

3. Therefore:
We don’t need to record the block hash of “height n” when it is “height n+1”, we can record the block hash of “height n” when it is “height n”

Comment (summerpro) [reply x/evm/keeper/abci.go:26]: GetHeight() has not changed, it will return the current height "n".

In the beginBlock stage of "height n", we can get the block hash by "RequestBeginBlock.Hash" of "height n" and the block hash by "RequestBeginBlock.Header.LastBlockId.Hash" of "height n-1".

File: x/evm/types/state_transition.go (hunk 4 above)
Comment (summerpro) [reply x/evm/types/state_transition.go:288]: Yes, it is compatible.We only need to get tendermint style hash in beginBlock stage, no longer need to recalculate according to tendermint hash algorithm

**Review by araskachoi — APPROVED** [review]
