### PR TITLE
fix transaction receipts 

### LINKED ISSUE #261: cannot get transaction receipt for contract deployments
__System info:__ branch: development

__Steps to reproduce:__

1. send some transaction, wait for it to be included, eg:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"data":"0x60806040526000805534801561001457600080fd5b5060d2806100236000396000f3fe6080604052348015600f57600080fd5b5060043610603c5760003560e01c80634f2be91f1460415780636deebae31460495780638ada066e146051575b600080fd5b6047606d565b005b604f6080565b005b60576094565b6040518082815260200191505060405180910390f35b6000808154809291906001019190505550565b600080815480929190600190039190505550565b6000805490509056fea265627a7a723158207b1aaa18c3100d8aa67f26a53f3cb83d2c69342d17327bd11e1b17c248957bfa64736f6c634300050c0032","from":"0xfe33d0a3efb35ab26fcbfb102e1663e068867ef1"}],"id":1}' -H "Content-Type: application/json" http://localhost:8545
```

2. try to get tx receipt (replace hash with tx hash returned in step 1)
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xcebbb6c7d109dcfa43983b776519194e02aa366dc4384164a12e85f578241b8b"],"id":1}' -H "Content-Type: application/json" http://localhost:8545``
```

3. error returned:
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"UnmarshalBinaryLengthPrefixed cannot decode empty bytes"}}
```

__Expected behavior:__ [What you expected to happen]
expected to retrieve transaction receipt

__Actual behavior:__ [What actually happened]

```{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"UnmarshalBinaryLengthPrefixed cannot decode empty bytes"}}

```

__Additional info:__ [Include gist of relevant config, logs, etc.]

### PR DESCRIPTION
**Pull request by noot**
Closes: #261 

## Description

- fix GetTransactionReceipt to return status=0 when no txData exists (since that means tx failed, but sdk doesn't set status to 0)
- add test for getting receipt from non-contract deployment transaction
- receipts working for the ethermnt deploy script and curl

Test instructions:
```
ETHERMINT_NODE_HOST=http://localhost:8545 ETHERMINT_INTEGRATION_TEST_MODE=stable go test ./tests/... -test.v -test.run ^TestEth_GetTransactionReceipt
```

curl instructions:
start daemon + client, then:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1}' -H "Content-Type: application/json" http://localhost:8545``
```

use resulting account as `from` of next step:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"data":"0x60806040526000805534801561001457600080fd5b5060d2806100236000396000f3fe6080604052348015600f57600080fd5b5060043610603c5760003560e01c80634f2be91f1460415780636deebae31460495780638ada066e146051575b600080fd5b6047606d565b005b604f6080565b005b60576094565b6040518082815260200191505060405180910390f35b6000808154809291906001019190505550565b600080815480929190600190039190505550565b6000805490509056fea265627a7a723158207b1aaa18c3100d8aa67f26a53f3cb83d2c69342d17327bd11e1b17c248957bfa64736f6c634300050c0032","from":"0xbda0d762653c606f9ee2e9e04eb6dd880d9c9db7"}],"id":1}' -H "Content-Type: application/json" http://localhost:8545
```

then use resulting hash in next step:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xc425cfa420e1a7b8ab57329e24666d3cc2e4cb1058e946c17726e3fb96a76153"],"id":1}' -H "Content-Type: application/json" http://localhost:8545
```

also, can do `node web3/deploy_contract.js` in ethermint-deploy repo (make sure to pull master)

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [x] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [x] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

File: tests/rpc_test.go [hunk 1]
```diff
@@ -261,14 +262,45 @@ func TestEth_GetFilterChanges_WrongID(t *testing.T) {
...
+
 // deployTestContract deploys a contract that emits an event in the constructor
 func deployTestContract(t *testing.T) hexutil.Bytes {
 	from := getAddress(t)
 
 	param := make([]map[string]string, 1)
 	param[0] = make(map[string]string)
 	param[0]["from"] = "0x" + fmt.Sprintf("%x", from)
-	param[0]["data"] = "0x6080604052348015600f57600080fd5b5060117f775a94827b8fd9b519d36cd827093c664f93347070a554f65e4a6f56cd73889860405160405180910390a2603580604b6000396000f3fe6080604052600080fdfea165627a7a723058206cab665f0f557620554bb45adf266708d2bd349b8a4314bdff205ee8440e3c240029"
+	param[0]["data"] = "0x60806040526000805534801561001457600080fd5b5060d2806100236000396000f3fe6080604052348015600f57600080fd5b5060043610603c5760003560e01c80634f2be91f1460415780636deebae31460495780638ada066e146051575b600080fd5b6047606d565b005b604f6080565b005b60576094565b6040518082815260200191505060405180910390f35b6000808154809291906001019190505550565b600080815480929190600190039190505550565b6000805490509056fea265627a7a723158207b1aaa18c3100d8aa67f26a53f3cb83d2c69342d17327bd11e1b17c248957bfa64736f6c634300050c0032"
```
Comment (noot) [inline tests/rpc_test.go:302]: bytecode from ethermint-deploy counter.sol

**Review by fedekunze — APPROVED** [review]
testedACK
