### PR TITLE
change eth_estimateGas to return hexutil.Uint64

### LINKED ISSUE #296: eth_estimateGas not working with metamask
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__

metamask sends a transaction with these params:
```
"txParams": {
          "from": "0x82d7323524903ee1c95d2b1053f1ad3d08e1af71",
          "to": "0xf737fd832edef1838301765bd5639cb233f86cd9",
          "nonce": "0x1",
          "value": "0x16345785d8a0000",
          "gas": "0x5208",
          "gasPrice": "0x33c812b00"
        }
```

however it fails to estimate the gas for this call:
`Failed to calculate gas defaults.`

this may be related to some internal errors happening with truffle, since truffle does a `.call()` before sending a tx which uses `eth_estimateGas`

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]

### PR DESCRIPTION
**Pull request by noot**
Closes: #296

## Description

- update eth_estimateGas to return hexutil.Uint64 as expected: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_estimategas
- add test case
- also, metamask no longer has "failed to estimate gas" in its logs (metamask -> settings -> advanced -> download state logs)

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [x] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

File: rpc/eth_api.go [hunk 1]
```diff
@@ -486,7 +486,9 @@ func (e *PublicEthAPI) EstimateGas(args CallArgs) (uint64, error) {
 	// TODO: change 1000 buffer for more accurate buffer (eg: SDK's gasAdjusted)
 	estimatedGas := simResponse.GasInfo.GasUsed
 	gas := estimatedGas + 1000
-	return gas, nil
+
+	ret := hexutil.Uint64(gas)
+	return ret, nil
```
Comment (fedekunze) [inline rpc/eth_api.go]:
```suggestion
	return hexutil.Uint64(gas), nil
```

**Review by fedekunze — APPROVED** [review]
